# Generated by Django 3.2.9 on 2021-12-06 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comtt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='insta.post'),
        ),
    ]
