# Generated by Django 3.2.9 on 2021-12-06 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0004_comment_comtt'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=200)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='static/profile/')),
                ('bio', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='comtt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='insta.post'),
        ),
    ]
