# Generated by Django 3.2.9 on 2021-12-08 09:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0007_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
