# Generated by Django 3.2.9 on 2021-12-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0008_alter_userdetail_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowersCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.CharField(max_length=1000)),
                ('user', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pk']},
        ),
    ]
